name: Test

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "corretto"
          java-version: 17

      - name: Grand permissions to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew --info test

      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/test/TEST-*.xml

      - name: Cleanup Gradle Cache
        if: ${{ always() }}
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
